language: generic

git:
  depth: 5

os: linux

dist: focal

before_install:
  - pip install --user pytidylib
  - pip install --user futures
  - git clone --depth=1 https://github.com/modelica-tools/ModelicaSyntaxChecker
  - git clone --branch 5.7.28 --depth=1 https://github.com/htacg/tidy-html5.git && ( cd tidy-html5 && cmake . && make && sudo make install )
  - sudo ldconfig

script:
  - python ./.CI/.travis.py tidyHTML ./
  - python ./.CI/.travis.py checkTags ./
  - if [[ "$TRAVIS_EVENT_TYPE" == "cron" ]]; then python ./.CI/.travis.py checkLinks ./; fi
  - "! find . -name '*.mo' -exec bash -c 'iconv -o /dev/null -f utf8 -t utf8 \"{}\" |& sed \"s,^,{}: ,\"' ';' | grep '.'"
  - ModelicaSyntaxChecker/Linux64/moparser -v 3.4 -r Complex.mo Modelica ModelicaReference ModelicaServices ModelicaTest ModelicaTestConversion4.mo ModelicaTestOverdetermined.mo ObsoleteModelica4.mo

notifications:
  email: false
